### ISSUE TITLE
error when running prismic sm --setup with npm

### ISSUE THREAD

**Issue by Dragana-Trgovcevic** [prismicio/prismic-cli#80]
I was running Node 15 which comes with npm version 7. Npm version 7 has changed the way that it handles peer dependency checks and failed to install most of the slice machine lnstall.
Once I figured out the issue was from the changes to npm I downgraded to node 14 and npm 6 and was able to get the prismic sm —setup to work for me. I submitted a pr to the libraries that seemed to be failing the dependency checks to update the versions allowed in the package.json. If there is a way to update the docs I would be happy to add info about the issues with node 15/npm 7 to them.
Related:
https://github.com/prismicio/prismic-cli/issues/77
https://github.com/prismicio/slice-machine/pull/77
https://github.com/prismicio/slice-machine/commit/c527a244f5142391a27455323027125aca09d5e4

https://community.prismic.io/t/prismic-sm-setup-error/3515   forum link

**Comment by lihbr** [comment]
Fixed 🙌 https://github.com/prismicio/slice-machine/commit/b131f90be582b6fc97f5c7b145b1a6afa156a41b

Thanks again~ ☺️

**Comment by darrenbarklie** [comment]
Hey @lihbr,

I still get warnings about this when installing with npm, in alignment with the documentation:
- node v14.15.4
- npm v7.5.3
- prismic v3.8.9

In practice, it hangs on the error from about 60 seconds, before eventually resolving to logic flow and "NEXT STEPS" screen. It caused me to abandon a few installation attempts before succeeding.

```
53 error ERESOLVE unable to resolve dependency tree
54 error
55 error While resolving: dazdotdev2@0.1.0
55 error Found: react@17.0.2
55 error node_modules/react
55 error   react@"17.0.2" from the root project
55 error   peer react@">=16.0.0" from prismic-reactjs@1.3.3
55 error   node_modules/prismic-reactjs
55 error     prismic-reactjs@"*" from the root project
55 error     peer prismic-reactjs@"^1.3.1" from essential-slices@1.0.3
55 error     node_modules/essential-slices
55 error       essential-slices@"*" from the root project
55 error
55 error Could not resolve dependency:
55 error peer react@"^16.13.1" from essential-slices@1.0.3
55 error node_modules/essential-slices
55 error   essential-slices@"*" from the root project
55 error
55 error Fix the upstream dependency conflict, or retry
55 error this command with --force, or --legacy-peer-deps
55 error to accept an incorrect (and potentially broken) dependency resolution.
```

**Comment by lihbr** [comment]
Hey @darrenbarklie, thank you so much for reporting that, we'll have a look at updating the default library with those, in the meantime you can safely uninstall it if you don't need default slices. I'm really sorry for the inconvenience there!

cc @a-trost
